import type { Metadata } from "next";
// import {  Geist_Mono } from "next/font/google";
import "./globals.css";
import { QueryClientProviderWrapper } from "@/components/query-client-provider";
import { AuthProvider } from "@/providers/auth-provider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "BESC - ID Card Generation | SnapCard",
  description: "Generated by DataChef",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <QueryClientProviderWrapper>
        <AuthProvider>{children}</AuthProvider>
        </QueryClientProviderWrapper>
      </body>
    </html>
  );
}
